### ISSUE TITLE
项目启动报错了

### ISSUE THREAD

**Issue by WQHASH** [jzfai/vue3-admin-template#25]
node 版本: v16.14.0
pnpm 版本：6.32.3
启动项目后正常运行，游览器报错；
TypeError: track(...) is not a function
 at Object.get (runtime-core.esm-bundler.js:2939:35)
    at ReactiveEffect.fn (index.ts:18:81)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at unref (reactivity.esm-bundler.js:1026:29)
    at Proxy.<anonymous> (input.vue:545:2)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5696:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5809:51)

**Comment by WQHASH** [comment]
解决了，pnpm 版本低于指定的版本（7.9.0）了

**Comment by WQHASH** [comment]
node为 >=16.0.0 的版本 ，pnpm 也换成7.9.0 版本还是报上面的错误！

**Comment by WQHASH** [comment]
解决了 pnpm 和 node 版本需要按照文档版本升级
