### ISSUE TITLE
 useBasicStore is not defined

### ISSUE THREAD

**Issue by ShamineDsouza** [jzfai/vue3-admin-template#26]
Kindly help, Dashboard not loading 

Uncaught (in promise) ReferenceError: useBasicStore is not defined
    at setup (index.vue:67:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5708:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)

![image](https://github.com/jzfai/vue3-admin-template/assets/25946929/8046093c-013e-41c3-88a2-0b457d0575d9)

**Comment by jzfai** [comment]
no found the issue
